### ISSUE TITLE
Recommend using Stylus instead of Stylish

### ISSUE THREAD

**Issue by tonin** [nileane/TangerineUI-for-Mastodon#10]
[Stylus](https://addons.mozilla.org/en-US/firefox/addon/styl-us/) is to be preferred to use a custom CSS for a single user as a Firefox Addon.  Stylish is even said to collect a lot of user data.

[Tapermonkey](https://addons.mozilla.org/en-US/firefox/addon/tampermonkey/) is also a nice alternative (can load JS as well).

**Comment by tonin** [comment]
Thanks!

And if I can have one more suggestion on the topic, sorry I should have added that right away, if you can add the following comments to your CSS file that would greatly help the import into the Stylish settings so that users can just do a cut&paste.

```
/* ==UserStyle==
@name         TangerineUI 🍊 for Mastodon
@version      0.9.2
@description  Tangerine UI is a UI revamp for Mastodon's Web interface. Last Mastodon compatibility check: v4.1.4 stable ✅
@namespace    http://www.w3.org/1999/xhtml
@author       @nileane@nileane.fr
@homepageURL  https://github.com/nileane/TangerineUI-for-Mastodon
@supportURL   https://github.com/nileane/TangerineUI-for-Mastodon/issues
@updateURL    https://github.com/nileane/TangerineUI-for-Mastodon/raw/main/TangerineUI-single-column.css
@license      MIT
@preprocessor default
==/UserStyle== */
```

**Comment by nileane** [comment]
I'm not sure if this would be the right call as I wish to keep maintaining this as a CSS file to be used by admins as well as users. Maybe I could include it in the README for people who wish to add it to the file?

**Comment by tonin** [comment]
Yes, you're absoluty right. Better keep your CSS file clean.
