### ISSUE TITLE
Left margin with the new CW

### ISSUE THREAD

**Issue by cadusilva** [nileane/TangerineUI-for-Mastodon#104]
Similar to #100, there's this left margin with the new CW appearance.

![image](https://github.com/user-attachments/assets/d5ea4411-6c9b-482f-946d-66a45a17d94e)

![image](https://github.com/user-attachments/assets/efca621a-487d-4278-8d8e-fcd41abf4bdb)

It also happens in the advanced interface:

![image](https://github.com/user-attachments/assets/caad1dba-146d-4693-b1f5-a7d062e2cd87)

![image](https://github.com/user-attachments/assets/cd724c78-2e10-4de9-8d43-b18e3a62378e)

Tested with LibreWolf 129 and Chromium 127. Mastodon `v4.3.0-alpha.5-62be023`.

**Comment by nileane** [comment]
Yep, I've still got to implement styling for the new CWs
