### ISSUE TITLE
Link to user profile "invades" post text area

### ISSUE THREAD

**Issue by cadusilva** [nileane/TangerineUI-for-Mastodon#105]
It's not always that this happens, but I noticed it a while ago and it's not rare. The user may end up opening the profile of themselves or someone else when trying to "expand" the post (as Mastodon calls it). The clickable link area hovers above the top of the post text area.

![Screencastfrom2024-08-2310-00-03-ezgif com-video-to-gif-converter](https://github.com/user-attachments/assets/fa826fb3-c226-43f5-801f-388b5e76346a)

The example post is long but happens with short ones too and gets in the way when you want to see the thread, for example, and ends up opening the profile of the user that sent the post.

**Comment by nileane** [comment]
I'm not able to reproduce this. Can you narrow down in which circumstances you're having this issue?

**Comment by cadusilva** [comment]
> I'm not able to reproduce this. Can you narrow down in which circumstances you're having this issue?

I also couldn't pinpoint what triggers this behaviour, but it's there. Just tried to open Chromium 127 to see if it wasn't something related only to LibreWolf/Firefox but...

![Screencastfrom2024-08-2310-19-27-ezgif com-video-to-gif-converter](https://github.com/user-attachments/assets/9dd4d669-314d-43a8-8213-9b46bb26be40)

Right at the first post in the timeline. Tested with the same post back in LibreWolf and the same thing happened. I have add-ons enabled in LibreWolf like Tampermonkey, but the same isn't true about Chromium.
