### ISSUE TITLE
Wishlist: Drop-down list when you hover over Explore or Live Feeds in the sidebar

### ISSUE THREAD

**Issue by p37307** [nileane/TangerineUI-for-Mastodon#108]
I'm not sure how many people use the Explore or Live Feed pages, I use them often. It would be great if when you Hover over the link in the sidebar it would drop-down the page links like hovering over Lists does. I know for me, with my Parkinsons, that would save me a couple clicks and improve my personal user experience. 

Explore
  – Posts
  – Hashtags
  – People
  – News

Live Feeds
  – This Server
  – Other Servers
  – All

Off Topic, nice clear UI, esp as an alternative for v4.3.* with its new "boxed" redesign.

**Comment by nileane** [comment]
Unfortunately, Tangerine UI relies only on CSS to customize Mastodon's interface. As a result, it would not possible to add elements that are not already there in the default UI.
