### ISSUE TITLE
Bad contract for hashtag suggestions in dark mode

### ISSUE THREAD

**Issue by Coukaratcha** [nileane/TangerineUI-for-Mastodon#11]
In dark mode, text color for `autosuggest-textarea__suggestions` is white (instead of black in white mode) but background color does not change. Hence, the contrast is very bad and text is not readable.

White mode (good)
![image](https://github.com/nileane/TangerineUI-for-Mastodon/assets/6431349/0cd700b3-65e0-43f7-bae9-38f11b16ab99)

Dark mode (bad)
![image](https://github.com/nileane/TangerineUI-for-Mastodon/assets/6431349/9c2dc141-aa2e-412b-9c27-fc8f78b95f06)

**Comment by nileane** [comment]
Thank you for reporting! :)
