### ISSUE TITLE
Post lower menu not having the correct color in dark mode

### ISSUE THREAD

**Issue by Kibranoz** [nileane/TangerineUI-for-Mastodon#111]
![image](https://github.com/user-attachments/assets/b3bba250-038c-45e7-8ecc-4a4a2194ce95)

It should be the same as the rest of the theme

**Comment by nileane** [comment]
You are probably not using the correct version of Tangerine UI that matches the version of your Mastodon instance. Please check the compatibility section in the README document: https://github.com/nileane/TangerineUI-for-Mastodon?tab=readme-ov-file#compatibility
