### ISSUE TITLE
No clear indicator for unread updates in timelines

### ISSUE THREAD

**Issue by novoid** [nileane/TangerineUI-for-Mastodon#119]
Hi,

# The situation with the default theme

While testing tangerineui-lagoon (looks amazing!) I noticed that there were no visual clues that a timeline has new messages as there is with the default (light) theme:

![image](https://github.com/user-attachments/assets/e3ecd80e-fdef-4fed-9c55-94f62138ea88)

You notice the shade in the middle of the line? That is this indicator that gives me a nudge that I may scroll up a bit to see that:

![image](https://github.com/user-attachments/assets/259c1d89-7b5f-48de-8e00-4620c61ee544)

(To be honest, I'd prefer to see the second view without having to manually scroll up but I guess this is not something a theme could change - correct me if I'm wrong here.)

# Using tangerineui-lagoon

With tangerineui-lagoon a similar situation looks like that:

![image](https://github.com/user-attachments/assets/cc524d34-ba66-465b-8f49-cb14c2af07b7)

Yes, there is some very fine line that indicates new messages but it's so subtle that I almost can't see it.

Furthermore, it's indistinguishable from the situation where I scroll in my TL and (by accident) happen to stop at the border of two messages. Scrolling through my TL:

![image](https://github.com/user-attachments/assets/b3fc5ba8-b3fa-40b5-8227-de3008c8d221)

... and now I scroll a bit more:

![image](https://github.com/user-attachments/assets/d8080673-4597-4508-85d2-c8f38872d616)

So I end up with the situation where it looks exactly like there are new messages in that TL but instead, there are only older ones I'm scrolling through.

# Current workaround (tedious)

In order to find out if there are new messages in a TL, I need to go through all of them, one by one, scroll up a bit and check if there appears something like that:

![image](https://github.com/user-attachments/assets/bf0d02de-f786-4792-9854-2e7d8f84c869)

# Proposed solution

I'd love to see a clearly visible indicator for new messages in a TL which is also clearly distinguishable from the in-between message indicator lines of the TL.

If possible, I want to get the last screenshot situation automatically when the interface detects new updates. And yes, I would not mind that my TLs get moved a bit when the interface detects new messages. YMMV.

**Comment by nileane** [comment]
Thanks!
This is a very good point, I will add this back :)
