### ISSUE TITLE
Current page title and page settings are misaligned on mobile

### ISSUE THREAD

**Issue by cadusilva** [nileane/TangerineUI-for-Mastodon#130]
As of right now, the name of the page/column/tab and its settings buttons are misaligned, hovering above other content like avatars.

![1-ezgif com-crop](https://github.com/user-attachments/assets/1128d174-35d5-4a42-88b3-635411f91635)
![2-ezgif com-crop](https://github.com/user-attachments/assets/8957c521-248c-40a4-b786-3fdc7a738634)

It only affects Tangerine UI themes.

Tested with `Fennec 132.0.0` and `Mulch Browser 130.0.6723.102`.

**Comment by nileane** [comment]
Fixed in #135
