### ISSUE TITLE
Account cards not styled for Dark Mode in Explore > For you view

### ISSUE THREAD

**Issue by Coukaratcha** [nileane/TangerineUI-for-Mastodon#19]
`account-card` blocks are not properly styled in dark mode in Explore > For you

Go to `<mastodon_url>/explore/suggestions` to reproduce.

Here is a screenshot:
![image](https://github.com/nileane/TangerineUI-for-Mastodon/assets/6431349/f2cb923a-9213-481c-9ab6-94ca651b77b1)

**Comment by nileane** [comment]
Fixed in https://github.com/nileane/TangerineUI-for-Mastodon/commit/389876137d9cbb9c2e2888b2465662b9d747fb89

Thank you for reporting :)
