### ISSUE TITLE
Icon for sharing options is hard to see in darkmode when boosting a post

### ISSUE THREAD

**Issue by MTRNord** [nileane/TangerineUI-for-Mastodon#22]
![image](https://github.com/nileane/TangerineUI-for-Mastodon/assets/1374914/33aaed0c-89d7-41fb-a43d-8d2889fe95f2)

Hi the contrast for the lock seems a little on the low side. Would be nice if that can be improved :) Otherwise this theme is really great and pretty! Thanks for the theme!

**Comment by nileane** [comment]
Hi!
Thank you for reporting!

Yea this definitely needs a fix so the lock icon uses the --color-content-fg variable.

Help me out, in which case are you getting this dialog? I cannot seem to find it

**Comment by nileane** [comment]
Thank you, It's fixed in https://github.com/nileane/TangerineUI-for-Mastodon/pull/24 :)

**Comment by MTRNord** [comment]
Awesome thanks!
