### ISSUE TITLE
Add support for the Advanced Web Interface

### ISSUE THREAD

**Issue by thomasmerz** [nileane/TangerineUI-for-Mastodon#27]
Your styles are really great and I love both of them ❤️ 
But I'm a little bit sad that they don't work when using extended webinterface… Can you or someone make them also work with that? Kind regards and greetings from [Germany](https://fulda.social/@abimelechbeutelbilch) 🇩🇪

**Comment by nileane** [comment]
I'm not planning to add support for the advanced web interface for now. But I might get on it at some point :)

**Comment by nileane** [comment]
Initial support for the advanced web interface has been added in Tangerine UI v2.0.0-prerelease2 https://github.com/nileane/TangerineUI-for-Mastodon/releases/tag/v2.0.0-pre2

**Comment by thomasmerz** [comment]
Thanks for this! ❤️ I tipped you a Ko-fi.
