### ISSUE TITLE
UserScript Support (CSP "Workaround")

### ISSUE THREAD

**Issue by Write** [nileane/TangerineUI-for-Mastodon#34]
# Hello, this thread is archived. We now have a [dedicated repo](https://github.com/Write/TangerineUI-Userscript) for this script. Every release after 1.2.5 can only be found [here](https://github.com/Write/TangerineUI-Userscript).
  
Everything below will stay as-is for documentation / archival purpose only.
Thanks !

____

Hi, thanks for your beautiful theme !

As I don't want to install Stylus, and use only Violentmonkey (userscript manager). 
I tried to find a way around Mastodon CSP rules (we can't just inject inline css).

For now, I found this workaround which works great for Mamot.fr instance. 
Unfortunately, raw.github.com sends `X-Content-Type-Options: nosniff`, which makes it unusable too.
Instead, we use jsdeliver which proxy the latest version of TangerineUI !

![Screenshot du 2023-07-19 à 02 35 10@2x](https://github.com/nileane/TangerineUI-for-Mastodon/assets/541722/bc539676-2cc5-49de-a38f-bf3cee8de76e)

# Usage
- Create a new userscript in either ViolentMonkey or Tampermonkey, and past the snippet below.
- Add a @match rule for each mastodon instance you want the theme to be enabled on.
- Change the styleUrl if you would like to try out the purple variant
- Enjoy :) !

# Changelog

### Release 1.2.5
+ Disable the script on page not stylized by TangerineUI anyway

### Release 1.2.4
+ Forcefully disconnect MutationObserver after 3 seconds if MutationObserver wasn't disconnect already
   _This fix a performance issue where MutationObserver would be running indefinitely if it never detected the element_
+ Apply background && background-color to \<body> tag yet again
+ Add a configurable timeout after how much time the css applied \<html> and \<body> should be reverted, default to 1 second

### Release 1.2.3
+ Now apply background color pre-emptively on either light or dark mode
   _This fix a flashing issue on load, if the instance main's theme was set as dark mode, but the system was in light mode_
+ The pre-emptively color set to \<html> is now dynamic, based selected theme (for light mode only, as dark mode as same color for both variants)
+ Correctly set background color in dark mode to TangerineUI Color instead of pure black

### Release 1.2.0
- "Production ready" code
- \<html> tag now injected instantly, as it doesn't require to wait for it.
- Moved from requestAnimationFrame to MutationObserver which should inject theme even faster. 
- Hugely improved code's readability
- Compatible with both Firefox and Chrome
- Support Safari, even though injection is slow, limited to requestAnimationFrame API as MutationObserver doesn't work most of the time (except when cache is cleared with CMD + SHIFT + R), certainly a limitation from how Safari handle extensions. Safari extension is : https://apps.apple.com/us/app/userscripts/id1463298887  -- Mac & iOS support. It support UserStyles too, so you could just create one instead.

# Userscript

 ```js
// ==UserScript==
// @name        TangerineUI 🍊 for Mastodon
// @match       https://mamot.fr/*
// @grant       none
// @version     1.2.5
// @author      @Write on Github
// @icon        data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAACE0lEQVR4AZXOA2xeUQAF4BvNW8xGi7WFY227v81otu0Fs23btq3attunvrN7//bOPMmX98414bFa4edyda12u7te0m8d1UKhRyNVT32idrtcGE6+jdMpBzjtUjOFf2KTZJddchKWsWPR22HprKLATBwnYOM6CfNni+Bjs2d0j02ZKLDOCVZrhx9xGNuT7aY2MAvmdKCjQwXP0UMidm4ToPYMiSKwcmkn+Hqbsd1L7LqWqTZ9M5injyXf4oN7O3HkQCdkGRAEFWdOCNi9vROKAnx8L4Ovt+uaZhCbpn6eTVsPpjBfRkN9F3ivLFfQ0qJ+6SXFCupqv86zvcSWVjPTml4DprhQRm21At7ZgbU1X3tBnoxGegHvlvSa2cSaUjXWklIJhh/Ae2Ge5DuA94JcyfdC3q2plVOJObncYU4qA1NcIPkO4H2soxLjXZW80wNEesDXeVNSqYcY44s1pvhiMDcvt+LB7Tbw/qPrF1rx+F77l25IKh1KjNEFw40xBfhfhpiCs4RFE/JxgDEqR6Xwj5qptZaot/0JjyE867UhPBOcMeJThCH8U6QhLNNgjMj06iMyjfQ/0RSROSQ2Nrc3+TG60I/J+tAPKgWfsI/7NaMe9SXfxBSbO4j8Kdrgdx5d0FuBQrd3zbrgN28Y2quofPK3aILeDtb6v1yt8X/5Suv/qo0Sdf6vijT+r05q/F9Hkl/kM/y+SpUd6mHfAAAAAElFTkSuQmCC
// @run-at      document-start
// ==/UserScript==

(function() {
    'use strict';

    // ----------------
    //   SETTINGS
    // ----------------
    // Reminder: Purple Variant URL
    // https://cdn.jsdelivr.net/gh/nileane/TangerineUI-for-Mastodon@main/TangerineUI-purple.css
    let styleUrl = '//cdn.jsdelivr.net/gh/nileane/TangerineUI-for-Mastodon@main/TangerineUI.css'
    const timeout = 1000;

    // -----------------
    //   HELPERS
    // -----------------
    const currentPagepath = window.location.pathname;
    const placeholder = 'TangerineUI 🍊';
    const log = (str) => console.log("* " + placeholder + " : " + str + " *");
    const theme = window.matchMedia?.("(prefers-color-scheme: dark)").matches ? "dark" : "light";
    const isPurple = styleUrl.match('-purple.css') ? true : false;

    const onElemAvailable = async selector => {
        while (document.querySelector(selector) === null) {
            await new Promise(resolve => requestAnimationFrame(resolve));
        }
        return document.querySelector(selector);
    };

    function createStyleNode() {
        var node = document.createElement('link');
        node.href = styleUrl;
        node.rel = 'stylesheet';
        node.media = 'all',
        node.type = 'text/css';
        return node;
    }

    // ----------------
    //   CODE
    // ----------------
    var isInjected = false;
    let backColor;
    let nChanges = 0;
    let timeoutExist = false;
    let mutationStatus = true;

    if (theme == 'light') {
        if (!isPurple)
            backColor = "#f5f2ef";
        else
            backColor = "#f2eff5";
    }
    else {
        backColor = "#030303";
    }

    // Prevent script from running on pages that are not styled by TangerineUI anyway.
    if (currentPagepath.startsWith("/auth") ||
        currentPagepath.startsWith("/settings") ||
        currentPagepath.startsWith("/relationships") ||
        currentPagepath.startsWith("/filters"))
    {
      return;
    }

    document.querySelector('html').style.setProperty("background", backColor, "important");

    setTimeout(function() {
        document.querySelector('html').style.background = '';
    }, timeout);

    new MutationObserver((mutations, observer) => {
        mutations.forEach(function(mutation) {

            var node, nodeType, href;

            if (mutation.addedNodes.length > 0) {
                node = mutation.addedNodes[0];
                nodeType = node.nodeName.toLowerCase();

                if (nodeType == 'link') {
                    if (node.href !== undefined) {
                        href = node.href;
                        const rChunk = /\/packs\/css\/mastodon.*\.chunk\.css/
                        const rCustom = /custom\.css/

                        // Inject after custom.css or mastodon.*.chunk.css, whichever is detected first
                        // On my system mastodon.*.chunk.css wasn't detected on Chrome
                        if (href.match(rCustom) || href.match(rChunk)) {
                            nChanges++;
                            isInjected = true;
                            document.head.appendChild(createStyleNode());
                            log('(MutationObserver) custom.css or mastodon.*.chunk.css detected, injected TangerineUI\'s css asap.');
                        }
                    }
                }
                if (nodeType == 'body') {
                    nChanges++;
                    node.style.setProperty("background", backColor, "important");
                    node.style.setProperty("background-color", backColor, "important");
                    setTimeout(function() {
                        node.style.background = '';
                        node.style.backgroundColor = '';
                    }, timeout);
                }

                /* All mutations are done (two changes)
                * Disconnect the observer */
                if (nChanges >= 2 && mutationStatus) {
                    mutationStatus = false;
                    observer.disconnect();
                }
            }

            /* In certain case, mutation never disconnect, for example in Safari,
            * when it doesn't detect .css file, and use requestAnimationFrame instead,
            * This timeout helps to be sure the MutationObserver is disconnected to avoid performance issues */
            if (!timeoutExist) {
                timeoutExist = true;
                setTimeout(function() {
                    if (mutationStatus) {
                        observer.disconnect();
                    }
                }, 3000);
            }

        });
    }).observe(document.documentElement, { childList: true, subtree: true });

    // Workaround if MutationObserver couldn't detect the item
    // Usually in Safari.
    onElemAvailable('link[rel^=stylesheet][href*=custom\\.css]').then(() => {
        if (!isInjected) {
            document.head.appendChild(createStyleNode());
            log("(requestAnimationFrame) custom.css detected, injected TangerineUI's css asap");
        }
    });

})();
```

**Comment by Write** [comment]
Added auto-update for both themes. 
Link for regular theme : https://socialspill.com/TangerineUI.css
Link for purple theme : https://socialspill.com/TangerineUI-purple.css

**Comment by Write** [comment]
Update :

I just discovered one can use jsdeliver to proxy the github's raw file, and thus bypassing the "nosniff" header / error. 
Which is great since it avoid the need to self-host or using my link.

Links for both themes :
https://cdn.jsdelivr.net/gh/nileane/TangerineUI-for-Mastodon@main/TangerineUI.css
https://cdn.jsdelivr.net/gh/nileane/TangerineUI-for-Mastodon@main/TangerineUI-purple.css

The tool I used : https://www.jsdelivr.com/github

**Comment by Write** [comment]
Huge update to inject the style as fast as possible, and a workaround to avoid the page bliking is to set html's background black if detected system theme is dark, and unset it after 1 second because it's not needed anymore (and would break if host system switch to light mode). We also add !important to body background-color so for the few milliseconds mastodon main's theme is loaded, it won't be able to enable it's background-color.

We unfortunatly can't import the theme before main's mastodon theme, thus we inject it after custom.css is detected in the <head>.

There seems to still be some flash from time to time, but it's way better now anyway.

**Comment by Write** [comment]
# Update 1.2.0

- "Production ready" code
- \<html> tag now injected instantly, as it doesn't require to wait for it.
- Moved from requestAnimationFrame to MutationObserver which should inject theme even faster. 
- Reduced code size and improved readability
- Compatible with both Firefox and Chrome
- Support Safari, even though injection is slow, limited to requestAnimationFrame API as MutationObserver doesn't work most of the time (except when cache is cleared with CMD + SHIFT + R), certainly a limitation from how Safari handle extensions. Safari extension is : https://apps.apple.com/us/app/userscripts/id1463298887  -- Mac & iOS support. It support UserStyles too, so you could just create one instead.

**Comment by nileane** [comment]
This is awesome :)
I have pinned this issue so it's easily accessibly.

If it's okay with you, I can also add a section in the README file redirecting to this thread.

**Comment by Write** [comment]
Perfect :) 
I updated to 1.2.1 already, uploaded wrong version.

**Comment by Write** [comment]
# Release 1.2.3

+ Now apply background color pre-emptively on either light or dark mode
   _This fix a flashing issue on load, if the instance main's theme was set as dark mode, but the system was in light mode_
+ The pre-emptively color set to \<html> is now dynamic, based selected theme (for light mode only, as dark mode as same color for both variants)
+ Correctly set background color in dark mode to TangerineUI Color instead of pure black

**Comment by Write** [comment]
@nileane Hello, tidied up the doc, and removed all my posts. Looking at the latest release (1.2.5), I decided to disable the script entirely on pages TangerineUI is not styling anyway, do you think there's more URL I can disable it too ? If you have any idea / room for improvement to tell me, please tell me 😃. Thanks.

**Comment by nileane** [comment]
The "Installation for regular users" section in README now references this script for users who wish to use it :) https://github.com/nileane/TangerineUI-for-Mastodon/commit/0aa945b81c93d50f2d7f3b8b403fe7c1fc957e98
