### ISSUE TITLE
Colour-scheme doesn't switch depending on system colour-scheme on Fedora Linux

### ISSUE THREAD

**Issue by thopanX** [nileane/TangerineUI-for-Mastodon#46]
First of all, great layout!

I'm encountering a slight problem on my Linux machine (latest Fedora, Gnome 44): Tangerine's colour-scheme doesn't switch depending on system colour-scheme (while it does on my Android phone and a Mac computer I have access to).

**Comment by nileane** [comment]
Hi, thanks!

I'm not sure what's causing the issue, maybe it's related to your desktop environment not supporting light and dark system settings and reporting them to your browser. Speaking of which, it might also be realted to the web browser you're using on Linux.

In any case, I'm just using standard @media queries in Tangerine UI, so this is not an issue on my end. :)
