### ISSUE TITLE
Notification filter bar broken with all categories displayed

### ISSUE THREAD

**Issue by nileane** [nileane/TangerineUI-for-Mastodon#48]
Notifications tab : if "Display all categories" is enabled, the filter bar looks broken.
Specific rules need to be set for its icons and margins

**Comment by eramdam** [comment]
IDK if it's related but the icons for polls and followers section have the accent color unlike the others 
![image](https://github.com/nileane/TangerineUI-for-Mastodon/assets/1409924/aa329e1c-eb6f-45f0-871f-9b780a73376c)

**Comment by nileane** [comment]
yep that's the one x)

**Comment by nileane** [comment]
![Safari - 2023-08-21 à 12 40@2x](https://github.com/nileane/TangerineUI-for-Mastodon/assets/914451/161bd623-d0db-49c0-9113-fec4dc4ab11e)
This is now fixed in the upcoming update
