### ISSUE TITLE
Top bar isn't displayed on mobile using Firefox for Android

### ISSUE THREAD

**Issue by Elsensee** [nileane/TangerineUI-for-Mastodon#49]
Love the design, but on mobile the top bar is hidden via `display: none;`.

I generally get why, because one might want the display space, but this bar can contain important functions, like:
- On home announcements and simple settings
- On notifications settings, especially about push notifications (super important if one uses the web app on mobile)
- In hashtag search results, the ability to follow a hashtag

I think, this should be added back to the view. :)

**Comment by nileane** [comment]
Mmh. I don't hide the top bar on mobile. 
It should be there. See here for a hashtag timeline for instance:

![Safari - 2023-07-31 à 15 52@2x](https://github.com/nileane/TangerineUI-for-Mastodon/assets/914451/b51a9cb9-e933-4e2f-ab15-b529cb86860c)

Which browser/phone are you using?

**Comment by Elsensee** [comment]
It is hidden here: https://github.com/nileane/TangerineUI-for-Mastodon/blob/5122648b0158d9e9e7a24c62392eec789f95fa71/mastodon/app/javascript/styles/tangerineui/layout-single-column.scss#L1606
It's a bit weird that it displays for you...

I'm using Firefox for Android 116.0b8

**Comment by Elsensee** [comment]
Oh I see... https://caniuse.com/css-has
It is disabled on Firefox...

**Comment by nileane** [comment]
Ah. Yep.

Ok I should try to implement a good fallback for Firefox.

Thank you for reporting!

**Comment by nileane** [comment]
Should be all good now :)
