### ISSUE TITLE
Firefox scrollbar isn't stylized

### ISSUE THREAD

**Issue by Write** [nileane/TangerineUI-for-Mastodon#51]
Unfortunatly Firefox doesn't support `-webkit-scrollbar`. 

While there's no way to change scrollbar width or margin, we can have the gutter transparent and color the thumb. 

For purple variant, you could add 

```
html {
    scrollbar-color: #6364ff transparent;
}
```

The result is as lovely as in other browser now ! 🌟

**Comment by nileane** [comment]
I will try this out, thanks! :)

**Comment by nileane** [comment]
I've been thinking about this, and I don't think I'm going to style the scrollbars for Firefox. The main reason I'm styling them for WebKit browsers is because there isn't a good way to completely revert to the system scrollbars, which is what I would rather do if I could.
