### ISSUE TITLE
[BUG] Trying to change to the theme post-installtion results in an error

### ISSUE THREAD

**Issue by yuvalne** [nileane/TangerineUI-for-Mastodon#53]
Downloaded the files using the `mastodon` user and edited the `themes.yml` file according to instructions, and run the RAILS command as well. After switching to root and restarting the Mastodon services, the theme was available to pick in `settings/preferences/appearance`, but picking either the regular or the purple results in a "_something went wrong on our end_" error:
![image1](https://github.com/nileane/TangerineUI-for-Mastodon/assets/97384040/b7bc888c-ae17-4049-a79f-73f7d2c91aa3)
The files all have the correct permissions, downloaded straight from GitHub's Raw page, the `themes.yml` fits the one shown in step 2.
<img width="543" alt="Screenshot 2023-08-07 at 20 23 10" src="https://github.com/nileane/TangerineUI-for-Mastodon/assets/97384040/3fe925ca-7b04-444e-91f9-8eca84f43b0b">
If a user picks either of the Tangerine themes, the error persists indefinitely. Neither the home page nor any of the setting pages are able to load, and just the error is shown. The only way to fix it is to remove (or comment out) the themes from the `themes.yml` file, which then reverts the theme for the user back to the instance default.

**Mastodon version**: vanilla Mastodon 4.1.6
**Instance**: toki.social

**Comment by nileane** [comment]
Were there any errors when you ran the RAILS command?
Somebody reported a similar issue: they ran the RAILS command but some assets didn't compile properly. They were still able to pick the theme in preferences but it resulted in the in the same issue you encountered. They later told me they were able to make it work by trying again.

**Comment by nehemiagurl** [comment]
(replying from my personal account) I actually started the whole thing over multiple times just to make sure the mistake isn't on my end and I can say for certain that there were no errors in the latest attempts while there still was this bug.
If you wish I can try and run the whole thing again and paste here the response I get from RAILS.

**Comment by nileane** [comment]
> If you wish I can try and run the whole thing again and paste here the response I get from RAILS.

That might help! :)

**Comment by nehemiagurl** [comment]
this is a long output, so here's a .txt dump
[rails.txt](https://github.com/nileane/TangerineUI-for-Mastodon/files/12371820/rails.txt)

**Comment by mathieugp** [comment]
I ran into what appears to be the same problem. I did not really notice anything out of the ordinary when running `RAILS_ENV=production bundle exec rails assets:precompile` ( I will come back to it and confirm that), but the puma logs says:

```
ActionView::Template::Error (Webpacker can't find tangerineui-purple.css in [...]/www/public/packs/manifest.json. Possible causes:
1. You want to set webpacker.yml value of compile to true for your environment
    unless you are using the `webpack -w` or the webpack-dev-server.
2. webpack has not yet re-run to reflect updates.
3. You have misconfigured Webpacker's config/webpacker.yml file.
4. Your webpack configuration is not creating a manifest.
```

The instance is v4.1.4, node v12.22.12, ruby ruby 2.7.4p191, Debian GNU/Linux 11.

**Comment by nehemiagurl** [comment]
My instance is also on Debian 11 and the same version of ruby. Interesting that it's the same 🤔

**Comment by nileane** [comment]
See https://github.com/nileane/TangerineUI-for-Mastodon/issues/62#issuecomment-1793576251

**Comment by nehemiagurl** [comment]
can confirm this as resolved in 4.2.3.

**Comment by nehemiagurl** [comment]
and it seems the issue returned in 4.3.0. exact same behaviour as last time: I had to comment out the themes (all of them, it seems) to be able to access my account. ruby version is 3.3.5p100.

**Comment by nehemiagurl** [comment]
well, doesn't seem to be the case anymore in 4.3.1. strange.

**Comment by questionlp** [comment]
I just ran into this issue with v4.3.1 (basically stock with only mods to increase post length and number of fields for users) using the install script. Thankfully I created a separate local branch for my Mastodon install so I could rollback cleanly.

I'll try the manual install process at some point.
