### ISSUE TITLE
notification checkbox and settings icon don't show up until page is huge

### ISSUE THREAD

**Issue by masukomi** [nileane/TangerineUI-for-Mastodon#54]
this is probably a side-effect of using large fonts (accessibility needs - default 20 min 18. note that using zoom is not the same and not a valid test for large fonts.) 

Unless i make my window really wide, i don't see the checkbox to mark all notifications read or the settings icon. 

this is my window at ~1000 pixels wide. 
![CleanShot 2023-08-15 at 08 24 30](https://github.com/nileane/TangerineUI-for-Mastodon/assets/2829/bede6a30-e77e-44bd-ae34-0eb0b2fda645)

I have to expand it to ~1170 to see the checkbox. 

![CleanShot 2023-08-15 at 08 24 48](https://github.com/nileane/TangerineUI-for-Mastodon/assets/2829/4f94c834-59c8-449a-9e17-31326e2f7170)

Pixels these days are weird but it feels like i have to make it way wider than i should in order to be able to see those. The default css has them always visible, which i would prefer.

**Comment by nileane** [comment]
Hi!

This is definitely a bug, the notification toolbar show be displayed no matter the window width.
Here's what it looks like on my end at 1000px wide:

![Safari - 2023-08-17 à 18 20@2x](https://github.com/nileane/TangerineUI-for-Mastodon/assets/914451/6ffa6ca9-e222-4f6c-97dc-c6c0c1048b45)

**Comment by nileane** [comment]
Can confirm, this is fixed if you install the latest version of Tangerine UI :)
