### ISSUE TITLE
"2375:19 Expected <num0-1> but found "20%"."

### ISSUE THREAD

**Issue by expertmanofficial** [nileane/TangerineUI-for-Mastodon#56]
Hi, please note that I don't selfhost anything, so I installed your theme via Stylus.

Below, you can see the full screenshot.
![image](https://github.com/nileane/TangerineUI-for-Mastodon/assets/119038242/03755c94-3d61-4ab3-a8fc-32625e9b1c20)

**Comment by nileane** [comment]
% values should be supported with fill-opacity now, but it seems it's not the case with all browsers.
So I'll be changing that value to 0.2
