### ISSUE TITLE
Fix CSS colors for the inputs on popup modals

### ISSUE THREAD

**Issue by expertmanofficial** [nileane/TangerineUI-for-Mastodon#57]
Basically, this screenshot should explain everything, I guess.
![image](https://github.com/nileane/TangerineUI-for-Mastodon/assets/119038242/275ab04e-b9db-4295-be2c-2900fe147565)

Context: I tried to boost [this post](https://oisaur.com/@renchap/110946204807935716) and saw that input in popup is colored incorrectly.

**Comment by NordineFR** [comment]
so you can use background color and add !important so it override any previews styles

 input{
  background-color : #D3D3D3 !important; 
}

**Comment by nileane** [comment]
Ah, this is caused by a change in Mastodon v4.2.0.
Will fix this, thanks!
