### ISSUE TITLE
Add support for the new bottom message hashtags

### ISSUE THREAD

**Issue by tcitworld** [nileane/TangerineUI-for-Mastodon#58]
Mastodon 4.2.0 will introduce these hashtags at the bottom of a post. They're in a `div.hashtag-bar`.

Example and screenshot:
https://mastodon.online/@Pepijn/110944144262753083

![image](https://github.com/nileane/TangerineUI-for-Mastodon/assets/2197836/fc00df0f-96a9-475a-b2b3-f4faae092ae1)

**Comment by nileane** [comment]
This is already done :) https://github.com/nileane/TangerineUI-for-Mastodon/releases/tag/v1.9-pre

(I will properly release Tangerine UI v1.9 when Mastodon 4.2.0 officially comes out)

**Comment by nileane** [comment]
Mmm, looks like they went for a subtler design.
Keeping this issue open until I adapt my current implementation.

**Comment by nileane** [comment]
This is now done in Tangerine v1.9 :) https://github.com/nileane/TangerineUI-for-Mastodon/releases/tag/v1.9
