### ISSUE TITLE
copy instructions in readme are not screen reader friendly

### ISSUE THREAD

**Issue by maeknight** [nileane/TangerineUI-for-Mastodon#59]
the instructions in the readme are not screen reader friendly and my instance admin is blind.

for example:

> 1. Copy the files from [this folder](https://github.com/nileane/TangerineUI-for-Mastodon/tree/main/mastodon/app/javascript/styles/) to your Mastodon themes directory `app/javascript/styles/`:
> 
> ```
> app/
>   javascript/
>     styles/
>       tangerineui.scss                                | **new**
>       tangerineui-purple.scss                         | **new**
>         tangerineui/                                  | **new**
>           layout-single-column.scss                   | **new**
>         tangerineui-purple/                           | **new**
>           layout-single-column.scss                   | **new**
> ```

it is not clear what needs doing based on this. instead it should make a clear instruction, and then explain that the code block that follows is an example of what this looks like:

> 1. Copy the files from [`mastodon/app/javascript/styles/`](https://github.com/nileane/TangerineUI-for-Mastodon/tree/main/mastodon/app/javascript/styles/) in this repository to your Mastodon themes directory `app/javascript/styles/`. when complete the folder should contain:
> 
> ```
> app/
>   javascript/
>     styles/
>       tangerineui.scss                                | **new**
>       tangerineui-purple.scss                         | **new**
>         tangerineui/                                  | **new**
>           layout-single-column.scss                   | **new**
>         tangerineui-purple/                           | **new**
>           layout-single-column.scss                   | **new**
> ```

the directory listing will still be inaccessible as it relies on indentation to indicate the relationship between each listing, however at least the instruction on what needs doing are clear. a better solutions would be appreciated.

**Comment by Here-Be-Saoirse** [comment]
the best way would be to format it as commands, like so

```
cd dir1
cp $INSTALLDIR/path/filename.ext .
cp $INSTALLDIR/path/filename1.ext .
cd ..
cd dir2
```
... and so on

Better still would be to have an installer script for this that can be run from ~/live in the mastodon user

**Comment by maeknight** [comment]
something like this?

> 1. **Copy the files** from `mastodon/app/javascript/styles/` [in this repository](https://github.com/nileane/TangerineUI-for-Mastodon/tree/main/mastodon/app/javascript/styles/) to your Mastodon themes directory `app/javascript/styles/`:
> 
> ```
> cp -r $REPO/mastodon/app/javascript/styles/* $INSTALLDIR/app/javascript/styles
> ```
> 
> 2. **Copy the files** from `mastodon/app/javascript/skins/vanilla/` [in this repository](https://github.com/nileane/TangerineUI-for-Mastodon/tree/main/mastodon/app/javascript/skins/vanilla/) to your Glitch-soc skins directory `app/javascript/skins/vanilla/`:
> 
> ```
> cp -r $REPO/mastodon/app/javascript/skins/vanilla/* $INSTALLDIR/app/javascript/skins/vanilla
> ```
>
> 3. **Compile theme assets and restart.** Run `RAILS_ENV=production bundle exec rails assets:precompile` and restart your Glitch-soc instance for the changes to take effect.

**Comment by nileane** [comment]
> the best way would be to format it as commands, like so
> 
> ```
> cd dir1
> cp $INSTALLDIR/path/filename.ext .
> cp $INSTALLDIR/path/filename1.ext .
> cd ..
> cd dir2
> ```
> 
> ... and so on
> 
> Better still would be to have an installer script for this that can be run from ~/live in the mastodon user

I wouldn't know how to make such a script, but if anyone wants to give it a try I will add it to the instructions :)

**Comment by nileane** [comment]
> something like this?
> 
> > 1. **Copy the files** from `mastodon/app/javascript/styles/` [in this repository](https://github.com/nileane/TangerineUI-for-Mastodon/tree/main/mastodon/app/javascript/styles/) to your Mastodon themes directory `app/javascript/styles/`:
> > 
> > ```
> > cp -r $REPO/mastodon/app/javascript/styles/* $INSTALLDIR/app/javascript/styles
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 
> > 2. **Copy the files** from `mastodon/app/javascript/skins/vanilla/` [in this repository](https://github.com/nileane/TangerineUI-for-Mastodon/tree/main/mastodon/app/javascript/skins/vanilla/) to your Glitch-soc skins directory `app/javascript/skins/vanilla/`:
> > 
> > ```
> > cp -r $REPO/mastodon/app/javascript/skins/vanilla/* $INSTALLDIR/app/javascript/skins/vanilla
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 
> > 3. **Compile theme assets and restart.** Run `RAILS_ENV=production bundle exec rails assets:precompile` and restart your Glitch-soc instance for the changes to take effect.

Alright, I'll edit the instructions to add commands.
Thank you for reporting this!
