### ISSUE TITLE
Adjusted compile command needed after upgrade to Mastodon v4.2.0

### ISSUE THREAD

**Issue by MiGrandjean** [nileane/TangerineUI-for-Mastodon#62]
Hi :)

I upgraded our Mastodon instance tonight from 4.1.9 to 4.2.0 and also updated TangerineUI to 1.9-pre.

Since the [`config/themes.yml`](https://github.com/mastodon/mastodon/blob/main/config/themes.yml) file changed, I re-added the TangerineUI themes there. When running `RAILS_ENV=production bundle exec rails assets:precompile` it simply told me: `Everything's up-to-date. Nothing to do`

However, restarting `mastodon-web.service` afterwards resulted in FATALs and made the webinterface unavailable:

```
Sep 21 21:51:23 mastodon bundle[30968]: F, [2023-09-21T21:51:23.136803 #30968] FATAL -- : [d2685765-a7ff-47a6-838e-16da87e4d759]
Sep 21 21:51:23 mastodon bundle[30968]: [d2685765-a7ff-47a6-838e-16da87e4d759] ActionView::Template::Error (Webpacker can't find tangerineui-purple.css in /home/mastodon/live/public/packs/manifest.json. 
```

While searching for a solution (pasting the error message into a search engine), I stumbled upon this [issue here](https://github.com/mastodon/mastodon/issues/27031). I then tried:

```
RAILS_ENV=production bundle exec rails assets:clobber assets:precompile
```

This worked fine :) I'm by no means a Ruby/Rails guy and I'm a bit out of my depth here, but I understand `assets:clobber` removes compiled assets first, so we have a clean slate and can then precompile anew. If I'm not completely wrong here, maybe this could be added to the README?

**Comment by MiGrandjean** [comment]
Oh, I'm really sorry, I should have read https://github.com/nileane/TangerineUI-for-Mastodon/issues/53 first 🤦‍♂
I guess it's the same issue.

**Comment by nileane** [comment]
Hi!
I'm definitely not a Ruby/Rails girl either, so I'm willing to trust you on this if perhaps you (or anyone else) can get confirmation that adding `assets:clobber` to the command can work in every case!

**Comment by nileane** [comment]
I haven't received any new reports regarding this issue, so I'm going to close it for now. I will reopen it if anything similar happens again and requires a change in the README instructions.
