### ISSUE TITLE
Contact infos are not easily available in the about page with large amount of text

### ISSUE THREAD

**Issue by wryk** [nileane/TangerineUI-for-Mastodon#65]
When the instance use a large amount of text the contact info is all the way down in the page

| Vanilla | Tangerine |
|--------|--------|
| ![Screenshot 2023-10-17 at 13-36-34 Eldritch Café](https://github.com/nileane/TangerineUI-for-Mastodon/assets/1964408/c9b69c56-e7c3-494c-a24e-a06f7ca0b3be) | ![Screenshot 2023-10-17 at 13-20-56 Eldritch Café](https://github.com/nileane/TangerineUI-for-Mastodon/assets/1964408/e0afcba8-129a-47cc-ab8c-b7d896cd86da) | 
| N/A | ![Screenshot 2023-10-17 at 13-38-38 Eldritch Café](https://github.com/nileane/TangerineUI-for-Mastodon/assets/1964408/f83a28d5-dc8d-4413-ab0a-e39342f2e126) |

**Comment by nileane** [comment]
I moved that card back at the top of the about page :)
Thank you! <3
