### ISSUE TITLE
Translation API

### ISSUE THREAD

**Issue by meghadeep-com** [nileane/TangerineUI-for-Mastodon#77]
Hi,

I had been testing the Tangerine Purple edition v2.0.0-prerelease, but it looks like it doesn't implement the Translation API in the web UI.

I am using LibreTranslate, and Mastodon 4.2.3, and if no custom CSS is chosen, I can see the Translate button with toots that are not in English.

**Comment by nileane** [comment]
Hi :)

Tangerine UI v2.0.0 improves translation by turning the "Translate" button into an actual button in the post's action bar, in the bottom right.
Can you see that button? 

![Safari - 2023-12-18 à 13 08](https://github.com/nileane/TangerineUI-for-Mastodon/assets/914451/886c0b56-1e4d-4f9a-9da0-3e99c29bf0fd)

**Comment by meghadeep-com** [comment]
That is entirely my bad, thank you!
