### ISSUE TITLE
Dark mode conflict, prerelease bug

### ISSUE THREAD

**Issue by dorkbuttt** [nileane/TangerineUI-for-Mastodon#78]
Been manually copying and pasting the purple variant 2.0.0prerelease version into Stylus on Firefox Nightly and been running into a theming issue where the composer options are not darkened with the rest of the site. 

<img width="308" alt="A screenshot of the post composer from Mastodon's web interface stylized by Tangerine UI, however as the background is dark, the container for composer actions is bright white." src="https://github.com/nileane/TangerineUI-for-Mastodon/assets/105171762/0b333ec8-24f1-48b6-a7c8-045b41c938c8">

**Comment by nileane** [comment]
This is not a bug. The compose field in Mastodon 4.3 has recently been redesigned and as a result Tangerine UI v2.0.0 is now supporting the new compose field. If your instance is not running the latest version of Mastodon 4.3 that contains this new compose field, it will not be styled properly like on your screenshot.

**Comment by nileane** [comment]
Also, as a reminder, please check the [Compatibility](https://github.com/nileane/TangerineUI-for-Mastodon#compatibility) section in the README.

Tangerine UI v2.0.0 should not be used with a Mastodon instance that's not been updated to Mastodon 4.3.

**Comment by dorkbuttt** [comment]
bah, i forgot to eyeball the versions. sorry about that!
