### ISSUE TITLE
old icon in "moved" banner occasionally covering new icon

### ISSUE THREAD

**Issue by nehemiagurl** [nileane/TangerineUI-for-Mastodon#79]
when viewing a moved account, the icon of the old account sometimes covers the icon of the new account.

this is a screenshot from 433.world, running v1.9.4:
<img width="697" alt="Screenshot 2024-01-01 at 12 21 30" src="https://github.com/nileane/TangerineUI-for-Mastodon/assets/109424320/1ca11207-4573-4951-a8ce-70c8d49a98db">
and this is from i1.no, running v2.0.0-prerelease:
<img width="700" alt="Screenshot 2024-01-01 at 12 13 11" src="https://github.com/nileane/TangerineUI-for-Mastodon/assets/109424320/8f0b718e-28c9-4012-97a2-bcacf8ba124d">
interestingly, on zeppelin.flights, which presumably also runs v1.9.4, this looks just fine:
<img width="696" alt="Screenshot 2024-01-01 at 12 15 37" src="https://github.com/nileane/TangerineUI-for-Mastodon/assets/109424320/83163f78-7563-4fa8-bb1a-88647ab89598">

(in all three cases the account previewed is the old FediTips account, @feditips@mstdn.social, although I've also seen this occur with other moved accounts.)

**Comment by nileane** [comment]
Ah, yes, I see where the issue is.
Thanks for reporting!
