### ISSUE TITLE
[v2.0.0] Boost icon visually disabled for our own followers-only toots

### ISSUE THREAD

**Issue by TixieSalander** [nileane/TangerineUI-for-Mastodon#80]
Hi! No biggy but I've spotted a little quirk (nothing catastrophic don't worry!)

## Issue
The boost button is visually disabled (opacity reduced to 20%) on our "Followers only" toots, even if its actually possible to boost them.

# Tested on

- On an instance running the Glitchsoc fork of Mastodon v4.3.0-alpha.0 
- with Tangerine UI [v2.0.0-pre3](https://github.com/nileane/TangerineUI-for-Mastodon/tree/v2.0.0-pre3)
- With the latest Tangerine UI code pushed on Github [on the day](https://github.com/nileane/TangerineUI-for-Mastodon/tree/aaae3d167840411062d4ab789735fbb0daded7a3) I post this.

## Example

<img width="383" alt="Exemple of one of my followers-only post with the rocket icon at 20% of opacity" src="https://github.com/nileane/TangerineUI-for-Mastodon/assets/2143796/ce12d7e4-c0a4-463a-973e-f2bf94b4e8a1">

**Comment by TixieSalander** [comment]
Changing this selector might do the trick:
```css
.app-body button.icon-button:is(
  .reblogPrivate, 
  .reblogPrivate:hover, 
  .disabled, 
  .disabled:hover
) .icon-retweet {}
```
to
```css
.app-body button.icon-button:is(
  .reblogPrivate:where(.disabled, [disabled]), 
  .reblogPrivate:where(.disabled, [disabled]):hover, 
  .disabled, 
  .disabled:hover
) .icon-retweet {}
```

**Comment by nileane** [comment]
Oh, good catch!
Thank you for the fix! :)
