### ISSUE TITLE
Setting to 'dark' from within Stylus breaks it?

### ISSUE THREAD

**Issue by thibaultmol** [nileane/TangerineUI-for-Mastodon#83]
Hi, I added the css (specifically the purple one) to Stylus and noticed that when I set it to Dark mode through stylus, the css stops working and the mastodon page returns back to normal.
I know your CSS auto detects system dark mode or browser dark mode but it seems like whatever kind of way Stylus uses to request dark mode, isn't being detected correctly?
![image](https://github.com/nileane/TangerineUI-for-Mastodon/assets/1010226/4621e2d3-ad09-4ca5-ba1b-62b502162b6b)

**Comment by nileane** [comment]
Hi. I am honestly not sure what the issue is here.
It might be worth reporting it to Stylus. Perhaps the extension is doing something specific in this case which breaks the CSS. All I know is the CSS Tangerine UI is simply using the standard prefers-color-scheme media query.
