### ISSUE TITLE
Low contrast for some "active" icons like boosts due to missing contrast makes it hard to recognise

### ISSUE THREAD

**Issue by thomasmerz** [nileane/TangerineUI-for-Mastodon#86]
When using Tangerine UI for Mastodon 🍊 with version: "v2.0.0-prerelease" and variant: "🍊 Tangerine" I sometimes find it very difficult to see "active" icons like boost or favorite due to low contrast (black/darkgray vs. purple on white background):

<img width="272" alt="image" src="https://github.com/nileane/TangerineUI-for-Mastodon/assets/18568381/68be42c5-f777-425b-ad30-f8ff8d61f83d">

Can you make this better with more contrast? For example also "orange"? Thanks in advance!

**Comment by nileane** [comment]
Hi, it looks like  you installed the wrong version of Tangerine UI. Until your Mastodon instance is upgraded to Mastodon 4.3, it is only compatible with Tangerine UI Legacy (v1.9.x).

See the compatibility section in the README document: https://github.com/nileane/TangerineUI-for-Mastodon?tab=readme-ov-file#compatibility

**Comment by thomasmerz** [comment]
Well you're right, but with 1.9.4 it's not much/real better/different 🤷🏼‍♂️ 

<img width="286" alt="image" src="https://github.com/nileane/TangerineUI-for-Mastodon/assets/18568381/dde0653a-0dae-4c4a-b1c0-9b55fca524e9">

**Comment by nileane** [comment]
Hmm. Something is not right. The custom icons are not appearing for you.
How are you installing the theme?

**Comment by thomasmerz** [comment]
I'm using https://github.com/openstyles/stylus/ in Firefox on MacOS:

<img width="925" alt="image" src="https://github.com/nileane/TangerineUI-for-Mastodon/assets/18568381/0c86a5f9-7558-4e98-8bfa-3853d798f1ba">
