### ISSUE TITLE
Theme signature stays on top of other elements

### ISSUE THREAD

**Issue by cadusilva** [nileane/TangerineUI-for-Mastodon#89]
Depending on the height of the content inside the column where the toot's publish field is or depending on the screen resolution/window size, the theme signature stays above other elements.

![image](https://github.com/nileane/TangerineUI-for-Mastodon/assets/8684263/a147bc2e-e3cd-4098-97fe-286c2e69b62b)

This happens only when using the advanced interface and prevents the use of a toot's publish box buttons. This issue is specially true when the screen size is something like 1366x768 (a user reported this to me).

**Comment by nileane** [comment]
Thanks :)
This should be fixed now
