### ISSUE TITLE
Suggestion: consider using lighter shades of black

### ISSUE THREAD

**Issue by cadusilva** [nileane/TangerineUI-for-Mastodon#90]
I'd like to suggest using lighter shades of black, like `--color-bg: #1c1c1c` as well as changing `--color-content-bg-focus` to some color that fits better with `#1c1c1c` (in this example) and other parts related.

As not everyone have an OLED screen to take advantage of such pitch black as currently is, it turns the dark theme "too dark". Something lighter would be also nicer, IMO.

**Comment by nileane** [comment]
I've gone back and forth a few times with the main shade of black in dark mode, and I think I'm going to stick with the current one (which is `#030303`, not `#000000`).

Apart from an aesthetic appreciation, does the darker shade pose any visibility issue? In my testing, going back to a slightly lighter shade would reduce contrast with several critical elements that I would also need to adjust as a result.

**Comment by cadusilva** [comment]
No, no, just aesthetic appreciation really. Anyway, thank you for considering the suggestion!
