### ISSUE TITLE
Support Glitch-Soc

### ISSUE THREAD

**Issue by omentic** [nileane/TangerineUI-for-Mastodon#92]
Hello! The README mentions that only the vanilla Mastodon flavour is supported for now. It would be nice to support the glitch-soc flavour as it would make using it on glitch-soc instances ever so slightly easier.

**Comment by nileane** [comment]
Hi! Unfortunately, I currently do not plan to support the glitch-soc flavor as I want to keep focusing on theming Mastodon's ever-evolving UI first and foremost.
