### ISSUE TITLE
Request: Dark/Light Mode Switcher Button

### ISSUE THREAD

**Issue by zoltrons** [nileane/TangerineUI-for-Mastodon#93]
Hello, can you please add a Dark/Light Mode Switcher for this UI. I'm using Firefox with RFP fingerprinting, which it causes all websites to think I'm using white theme default. So I can't use the dark variant of this theme. A simple switch would help users like me enjoy this beautiful UI without burning their eyes.

**Comment by nileane** [comment]
Hi, since Tangerine UI is simply a CSS-only custom theme on top of the default UI, it's impossible for me to add a button to manually switch between light or dark mode if it's not already there by default.
