### ISSUE TITLE
On mobile, in the "publish" view, avatars are over the header

### ISSUE THREAD

**Issue by elegaanz** [nileane/TangerineUI-for-Mastodon#94]
A picture is worth a thousand words:

<img src="https://github.com/nileane/TangerineUI-for-Mastodon/assets/16254623/14b0163b-5c45-4184-865e-deb21e928468" alt="A screenshot of the bug" height="600" />

I would expect my avatar to be cropped because it is under the header, but it is not because its `z-index` seems wrong.

I had to scroll to notice the bug, but it can also be seen if you reply to some other messages that is relatively long (in that case, it will be the avatar of the person you are replying to that will be over the header).

I'm using Firefox, if that matters.

**Comment by nileane** [comment]
Thanks for reporting :)
This should fix it

**Comment by elegaanz** [comment]
Thank you! :)
