### ISSUE TITLE
User avatar is too big in the "More from" bar

### ISSUE THREAD

**Issue by cadusilva** [nileane/TangerineUI-for-Mastodon#99]
This is how the avatar in the "more from" bar looks like in the notifications page or column. It's way bigger than it should.

![image](https://github.com/user-attachments/assets/efb27637-b853-4f5a-b448-ce6415618024)

Bellow is how it is seen in the default theme:

![image](https://github.com/user-attachments/assets/0cd09c78-e9d7-4323-a00f-08ddb3468b51)

LibreWolf 128.0.3-2, Debian Linux.

**Comment by nileane** [comment]
![Safari - 2024-08-16 à 19 36@2x](https://github.com/user-attachments/assets/9d827ca5-4bcf-46f4-beca-18aeca5a66f3)

I'm not able to reproduce the issue on my end, are on you Mastodon's main branch?

**Comment by cadusilva** [comment]
Yes, `main` branch currently @ commit `9194197`. But it only happens in the notification page/column, not when you "expand" a toot or see it in other timelines.

Notification page:
![image](https://github.com/user-attachments/assets/d90ee346-aabf-4047-a0c4-42b0a086436e)

"Expanded" toot in a column:
![image](https://github.com/user-attachments/assets/e1dc56a5-a50d-4c0d-a5e5-4686552e60f4)

Happens with other people toots, too. Like this one, that was edited after published and I got a notification about it:
![image](https://github.com/user-attachments/assets/e670d717-2ed0-4087-ae46-1570612b76e4)
